In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("concurrent_counter_result.csv")
df.head()

,threads,increments_per_thread,mutex_ms,mutex_eb_ms,cas_ms,cas_eb_ms,fetch_add_ms
0,1,100000,2.0285,1.5460,1.3908,1.4133,0.9101
1,2,100000,7.9269,21.5548,14.0705,15.8651,3.2377
2,4,100000,11.8028,90.4480,34.4507,49.9153,9.6775
3,8,100000,54.3797,423.8770,90.0776,125.0330,19.8930
4,12,100000,96.2908,952.8360,206.6010,264.5840,33.1437

In [ ]:
grouped_means = df.groupby('threads')[['mutex_ms', 'mutex_eb_ms', 'cas_ms', 'cas_eb_ms', 'fetch_add_ms']].mean().reset_index()
grouped_means

   threads    mutex_ms  mutex_eb_ms      cas_ms  cas_eb_ms  fetch_add_ms
0        1    2.609845     2.753535    2.100490    2.11626      1.373055
1        2   10.052680    29.188245   13.574525   14.79551      4.853100
2        4   13.002090    98.770740   40.021960   48.94440      9.476425
3        8   47.589365   431.981750  113.978280  136.50777     22.816130
4       12   90.336765  1053.001000  254.132500  300.72765     36.882150
5       16  131.263300  1979.372000  487.850800  551.30345     54.853080
6       20  174.930300  2497.152500  623.759650  695.32190     63.266290